### ISSUE TITLE
Do we need to grant any permissions to the token when using inside Github actions

### ISSUE THREAD

**Issue by anzxcolinlcc** [hectcastro/gh-metrics#43]
Hi @hectcastro , I am getting am empty table in the result,

![Screen Shot 2022-10-13 at 9 05 03 pm](https://user-images.githubusercontent.com/4087822/195568185-08d1b698-b4cd-4210-ac42-095aff2a23ac.png)

I am wondering if any of the perm listed below - would need to be added to the github token ( I am running the gh metrics command inside github action workflow)
https://docs.github.com/en/rest/overview/permissions-required-for-github-apps

**Comment by hectcastro** [comment]
Hm. This may be dependent on the repository you are trying to interact with (e.g., if it is private, but not the same repository you're running the workflow from).

I assembled the following test workflow, and it appears to be [working as expected](https://github.com/hectcastro/gh-metrics/actions/runs/3242082180):

```yaml
name: Test

on:
    push:
        branches:
            - gh-actions-test

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: |
            gh extension install hectcastro/gh-metrics
            gh metrics --owner cli --repo cli
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

See: https://github.com/hectcastro/gh-metrics/compare/gh-actions-test
